### ISSUE TITLE
rheadmar's checklist

### ISSUE THREAD

**Issue by rheadmar** [githubteacher/miniature-spork#2]
# things I am working on in this project

- [x] create branch
- [x] work locally
- [x] create commits
- [ ] create pull request
- [ ] explore git hub
- [ ] understand use cases for wiki and projects
- [ ] look into pulse and graphs
